# Implements SPEC-0001 SS 3.3 (per-run README.md).
"""Write the auto-generated provenance README for one run."""

from __future__ import annotations

import platform
import sys
from pathlib import Path

from aic2026.models.metrics import AggregateMetrics


def write_readme(metrics: AggregateMetrics, output_dir: Path, *, tasks_path: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    body = _render(metrics, tasks_path=tasks_path)
    (output_dir / "README.md").write_text(body, encoding="utf-8")


def _render(metrics: AggregateMetrics, *, tasks_path: Path) -> str:
    lines: list[str] = [
        f"# Run provenance - `{metrics.system}` at `{metrics.run_id}`",
        "",
        "Auto-generated by `bin/eval` (SPEC-0001 Tier 1).",
        "",
        "## Environment",
        "",
        f"- Python: `{platform.python_version()}` ({sys.implementation.name})",
        f"- Platform: `{platform.platform()}`",
        f"- Git SHA: `{metrics.git_sha or '(unavailable)'}`",
        f"- Tasks path: `{tasks_path}`",
        f"- Tasks evaluated: `{metrics.n_tasks}`",
        "",
        "## Headline numbers",
        "",
        f"- Overall mean R@1: **{metrics.overall.mean_r_at_1:.3f}**",
        f"- Overall mean R@5: **{metrics.overall.mean_r_at_5:.3f}**",
        f"- Overall mean R@10: **{metrics.overall.mean_r_at_10:.3f}**",
        f"- Overall mean MRR: **{metrics.overall.mean_mrr:.3f}**",
        f"- Latency p50/p95/p99 ms: **{metrics.latency.p50_ms:.1f}** / "
        f"**{metrics.latency.p95_ms:.1f}** / **{metrics.latency.p99_ms:.1f}**",
        "",
        "## Files in this directory",
        "",
        "- `metrics.json` - machine-readable; SPEC-0001 AC4.",
        "- `report.html` - human-readable summary; SPEC-0001 AC1.",
        "- `README.md` - this file.",
    ]
    return "\n".join(lines) + "\n"
