# Proves SPEC-0024 AC3: remote-job-exec auto-generates a valid run_id when
# --run-id is omitted, and honors it when given. Uses a throwaway registered
# job that captures the RunContext it receives.

from __future__ import annotations

from typing import Any

from typer.testing import CliRunner

from aic2026.cli.remote_job_exec import app
from aic2026.remote.context import RUN_ID_PATTERN
from aic2026.remote.registry import register

_CAPTURED: dict[str, Any] = {}


@register("runid-probe")
def _probe(ctx, config):
    _CAPTURED["ctx"] = ctx
    _CAPTURED["config"] = config


def test_run_id_autogenerated_when_omitted_AC3(tmp_path) -> None:
    _CAPTURED.clear()
    runner = CliRunner()
    result = runner.invoke(app, ["runid-probe", "--out", str(tmp_path / "out")])
    assert result.exit_code == 0, result.output
    ctx = _CAPTURED["ctx"]
    # Auto-generated id must satisfy the strict RunContext pattern.
    assert RUN_ID_PATTERN.fullmatch(ctx.run_id), ctx.run_id
    assert "runid-probe" in ctx.run_id


def test_explicit_run_id_is_used_AC3(tmp_path) -> None:
    _CAPTURED.clear()
    rid = "abc1234-runid-probe-20260530T010203Z"
    runner = CliRunner()
    result = runner.invoke(app, ["runid-probe", "--run-id", rid, "--out", str(tmp_path / "out")])
    assert result.exit_code == 0, result.output
    assert _CAPTURED["ctx"].run_id == rid


def test_config_forwarded_to_job_AC3(tmp_path) -> None:
    _CAPTURED.clear()
    runner = CliRunner()
    result = runner.invoke(app, ["runid-probe", "--out", str(tmp_path / "out"), "--config", "k=v"])
    assert result.exit_code == 0, result.output
    assert _CAPTURED["config"] == {"k": "v"}
